name: TAS Sync Check

on:
  pull_request:
    branches: [dev]

jobs:
  check:
    strategy:
      matrix:
        tas:
          - name: Celeste 100%
            url: "https://github.com/VampireFlower/CelesteTAS/archive/97be00d13323487e595a537407dae0a3bfe281a8.zip"
            path: "CelesteTAS-97be00d13323487e595a537407dae0a3bfe281a8/0 - 100%.tas"

          - name: Strawberry Jam All Levels
            url: "https://github.com/VampireFlower/StrawberryJamTAS/archive/5e015ce6882b00f96910613192700f71333073c5.zip"
            path: "StrawberryJamTAS-5e015ce6882b00f96910613192700f71333073c5/0-SJ All Levels.tas"
            bundle: "https://celestemodupdater.0x0a.de/pinned-mods/StrawberryJam2021-Bundle-78c358fa.zip"

    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: ${{ matrix.tas.name }}

    steps:
    - uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Wait for Azure build on commit ${{ github.sha }}
      run: cd .github/tas-check && ./1-get-build-url.sh "${{ github.sha }}"

    - name: Install Everest and required mods
      run: cd .github/tas-check && ./2-1-install.sh "${{ matrix.tas.url }}" "${{ matrix.tas.bundle }}"

    - name: Run TAS at ${{ matrix.tas.path }}
      run: cd .github/tas-check && ./3-run.sh "${{ matrix.tas.path }}"
